src/main/webapp/basic-search-helper.js, src/main/webapp/intrigue-api/cql.js, src/main/webapp/time-range.js
Using iso strings for dates instead of passing date objects so that
the query tool always returns valid filter tree data structures
Removing use of ES6 Set in favor of Immutable
=> Date Serialization Fix

src/main/webapp/maps/world-map.js
WorldMap has an infinite recursion bug in the effect for detecting parent element resizing.
=> Fixing bug that crashes Workspaces when the map is shown

package.json, yarn.lock
Updated GeospatialDraw dependency to use hash instead of branch so builds are reproducible.
=> Updated GeospatialDraw dependency to use hash instead of branch

package.json, src/main/webapp/location/bbox.tsx, src/main/webapp/location/coordinate-list.tsx, src/main/webapp/location/geolocation.stories.js, src/main/webapp/location/line.tsx, src/main/webapp/location/point/point-dms.tsx, src/main/webapp/location/point/point-usng.tsx, src/main/webapp/location/point/point-utm.tsx, src/main/webapp/location/polygon.tsx, src/main/webapp/location/with-coordinate-unit-tabs.tsx, yarn.lock
Added location input for line, polygon, and bounding box using GeospatialDraw.
GeospatialDraw Revelio branch: https://github.com/connexta/geospatialdraw/tree/revelio
Screenshots:
=> Added location input for line, polygon, and bounding box.

src/main/java/org/codice/ddf/catalog/direct/CatalogMethods.java, src/main/java/org/codice/jsonrpc/JsonRpcHttpServlet.java
- Binary metacard attributes are now base64 encoded instead of a list of integers
- Added iso8601 date formatting for GSON
=> Base64 and date fix

src/main/graphql-server/helpers/renderer.js, src/main/graphql-server/middleware.js, src/main/webapp/intrigue-api/context.js, src/main/webapp/intrigue-api/graphql.js, src/main/webapp/intrigue-api/schema.js
The resolver context sets up all the clients (fetch/jsonrpc) to interact
with DDF. When using the schema link, we need to ensure resolvers still
get clients or they won't be able to communicate with DDF. Those clients
also need access to the current HTTP request to pull auth info from
headers.
=> Fix SSR rendering by sharing the resolver context.

src/main/graphql-server/helpers/renderer.js
When the CSS was being rendered into the style tag, it was being HTML
encoded producing invalid CSS. `dangerouslySetInnerHTML` can be used to
prevent this.
=> Prevent font flash by preventing SSR CSS escaping

src/main/webapp/basic-search-helper.js
When there is no location in basic search we get an undefined error. This change fixes that.
=> Fixing bug when basic search is used without a location.

src/main/webapp/intrigue-api/fetch.js
Allow manual override of fetch client Origin header for cases when
`DDF_LOCAITON` is different from the required origin header.
=> Updates DDF fetch client

src/main/webapp/query-filters/filter-input/boolean-filter.tsx, src/main/webapp/query-filters/filter-input/location-filter.tsx, src/main/webapp/query-filters/filter-input/number-filter.tsx, src/main/webapp/query-filters/filter-input/text-filter.tsx, src/main/webapp/query-filters/filter/attribute-dropdown.tsx, src/main/webapp/query-filters/filter/comparator-dropdown.tsx, src/main/webapp/query-filters/filter/filter-group.tsx, src/main/webapp/query-filters/filter/filter-utils.tsx, src/main/webapp/query-filters/filter/index.tsx, src/main/webapp/query-filters/filter/individual-filter.tsx, src/main/webapp/query-filters/filter/operator.tsx, src/main/webapp/search-forms/editor.tsx, src/main/webapp/search-forms/route.tsx
Importing all of material-ui, while it might get dead code eliminated,
still adds a large amount of overhead to our build.
=> Fix build performance regression

package.json, src/main/webapp/basic-search-helper.js, src/main/webapp/location/filter.tsx, src/main/webapp/location/geo-to-wkt.tsx, src/main/webapp/location/keyword/index.spec.js, src/main/webapp/location/location.stories.js, src/main/webapp/maps/cluster-map.stories.js, src/main/webapp/maps/map-style.js, src/main/webapp/maps/world-map.stories.js, yarn.lock
Loading point radius search geometry from DDF causes the Workspace to crash. This was due to a mismatch between the format for buffer values in DDF an GeospatialDraw. This fix updates GeospatialDraw to match DDF resolving the error.
=> Fixed bug with loading point radius geometry from DDF.

src/main/webapp/basic-search-helper.js, src/main/webapp/location/with-draw-button.tsx, src/main/webapp/query-filters/filter-input/location-filter.tsx, src/main/webapp/query-filters/filter/index.tsx, src/main/webapp/query-filters/filter/search-geo-factory.tsx, src/main/webapp/workspaces/query-selector.js
Persisted the isDrawing state when the QuerySelector closes and added a React effect to listen for when drawing completes so that the popup can be reopened with the updated GeometryJSON thus restoring the Draw button functionality.
=> Fixed Draw button in QuerySelector popup

src/main/webapp/sources.js
When a user was unauthenticated `props.sources` was undefined, which would cause the page to break.
=> Small fix for sources

src/main/webapp/histogram.js
Fixing a bug that was added when I refactored to splitting multi valued
attributes.
I was replacing the result in the list instead of pushing the result to the list.
=> Histogram multi valued attribute fix

src/main/webapp/intrigue-api/metacards/metacards.js
Fixes this error that occurs when loading workspaces that have queries
=> Fix queries resolver

package.json, src/main/webapp/basic-search.js, src/main/webapp/intrigue-api/metacards/metacards.js, src/main/webapp/routes.js, src/main/webapp/search/details.js, src/main/webapp/search/results.js, src/main/webapp/search/search-routing.js, src/main/webapp/search/search.js, yarn.lock
Adds an example of a URL driven set of pages that act as a hybrid application when combined with SSR.  Also fixes the paging parameters by replacing the CQL paging parameters with the JSON RPC paging parameters. 
http://localhost:8080/search/catalog/search
http://localhost:8080/search/catalog/search/results?query=jpg&type=text&startIndex=1&pageSize=15
http://localhost:8080/search/catalog/search/results?query=jpg&type=image&startIndex=1&pageSize=15
http://localhost:8080/search/catalog/search/results/e0e485c32e8b47a0acd1773074b004d5
=> Add page based search

src/main/webapp/intrigue-api/metacards/CQLUtils.js
Enables geometry sanitization for CQL strings containing WKTs with spaces between the type and the opening parenthesis
=> Fix WKT sanitization regex

src/main/webapp/retry/retry.js, src/main/webapp/workspaces/workspaces.js
Network retries were previous popping up for workspace retrieval failures. This is unnecessary to retry when the user isn't logged in. Added a set to ignore certain graphQL errors, such as authentication.
=> Removes network retries for unauthenticated users

src/main/webapp/index-cards/index-cards.js
When action dialogs were a child of `CardActionArea`, that caused flickering on the index cards when clicking on said dialogs. 
I believe the reason `stopPropagation` does not work here is because the ripple effect is done with css
This effect can be seen in the gif posted in this PR: https://github.com/connexta/revelio/pull/207
=> Fix Flickering of Index Cards

src/main/webapp/basic-search.js, src/main/webapp/search/details.js, src/main/webapp/user-settings/result-form-select.js
- Fixes unique graphql query names
In order to prevent this in the future, you have to make sure the names given to graphql queries are unique. You can see the issue in VSCodes output tab, and the autocomplete for graphql inside of `gql` tags will stop working.
This fix affects you if you have this plugin (which you should)
=> Remove duplicate graphql query names

src/main/webapp/components/user-settings/user-settings.js, src/main/webapp/components/user/user.js
Moves Retries to within the user/user settings drawers to be less intrusive.
Fixes: https://github.com/connexta/revelio/issues/229
User Settings: 
User:
=> User Error Styling Fixes

src/main/configuration.js, src/main/webapp/components/network-retry/index.tsx
url.parse throws an error if the environment variables are undefined
=> Fix Config

src/main/webapp/components/thumbnail/thumbnail.stories.js
The default value should be the value, not the key.
Was causing the `Success` thumbnail story to display an error symbol on load
=> Fix Thumbnail Story

src/main/webapp/components/basic-search/basic-search-helper.js, src/main/webapp/components/basic-search/basic-search.js, src/main/webapp/components/query-builder/query-builder.tsx, src/main/webapp/components/query-builder/query-settings.tsx, src/main/webapp/components/query-builder/types.tsx, src/main/webapp/components/search-forms/editor.tsx, src/main/webapp/components/simple-search/simple-search.js, src/main/webapp/components/sort-order/sort-order.js, src/main/webapp/components/user-settings/search-settings.js, src/main/webapp/components/user-settings/source-select.js, src/main/webapp/react-hooks/use-query-executor.js
value was accidentally wrapped in an array which caused user preferences to break when selecting sources
also relaxes a couple checks
- Changes names of sources/sorts inside search forms  to mirror metacard schema
- Updates name of sources inside query executor to mirror json rpc schema
=> Fix Sources Settings Regression

src/main/webapp/components/basic-search/basic-search.js, src/main/webapp/components/query-builder/query-builder.tsx, src/main/webapp/components/query-editor/query-editor.tsx, src/main/webapp/react-hooks/use-anchor-el.tsx
This pr lets us add a three dot menu in the top section of the query editor, which will be used in switching between different search forms.
=> Extract header section from query builder

src/main/webapp/components/query-editor/query-editor.tsx, src/main/webapp/components/query-manager/add-query.tsx, src/main/webapp/components/query-manager/query-editor-popover.tsx, src/main/webapp/components/query-manager/query-manager.stories.tsx, src/main/webapp/components/query-manager/query-manager.tsx, src/main/webapp/components/query-manager/types.tsx, src/main/webapp/components/workspace/workspace.js
This pr makes workspace queries always have the same form, instead of being possibly transformed into a executable query. Doing this will aid in not having to transform these queries when doing create or save mutations.
=> Normalize queries on workspaces

src/main/webapp/intrigue-api/user/user.js
This was causing issues when user preferences were uninitialized because the typename for `template` isn't defined on load
=> Add Default Search Form To Default Preferences

src/main/webapp/components/confirm-delete/confirm-delete.js, src/main/webapp/components/index-cards/index-cards.js, src/main/webapp/components/index-cards/index-cards.stories.js, src/main/webapp/components/metacard-interaction/metacard-interactions-dropdown.tsx, src/main/webapp/components/query-manager/query-manager.tsx, src/main/webapp/components/result-forms/route.js, src/main/webapp/components/search-forms/container.tsx, src/main/webapp/components/search-forms/route.tsx, src/main/webapp/components/search-forms/search-forms.stories.tsx, src/main/webapp/components/sharing/sharing-modal.js, src/main/webapp/components/workspace/workspace-context.js, src/main/webapp/components/workspace/workspace.js, src/main/webapp/components/workspaces/workspaces.js, src/main/webapp/react-hooks/use-get-permissions.tsx
Also adds context to workspaces so that security attributes can be passed down for query cards to show available actions. https://github.com/connexta/revelio/pull/333/commits/904b35a44d5821b60a3ac11e81e542bda775d188
=> Change metacard interactions to use permissions hook

src/main/webapp/intrigue-api/metacards/metacards.js
If you didn't manually send the list of query ids it would set them to null
=> Fix Partial Updates to Workspaces

package.json, scripts/generate-schema-json.js
- Run `yarn graphql:schema` with dev server running and `schema.json` will automatically be updated.
=> Automatically generate schema using http request

src/main/webapp/intrigue-api/metacards/metacards.js
- Federated queries were not returning results in workspaces however in simple-search they were -https://github.com/connexta/revelio/issues/318
=> Fix Federated Source Query in Workspaces

src/main/webapp/components/basic-search/basic-search.js, src/main/webapp/components/simple-search/simple-search.js
When doing a simple search for a specific source all sources are still queried 
Fixes: #345
When use-query-executor was bieng called for `onSearch` a check exists wether or not `sourceIds` exist or not. if they dont query all sources. in Simple Search `sources` was being passed rather than `sourceIds` which caused it to query all sources
=> Fix Query in simple search when selecting sources

src/main/webapp/components/results/result-material-table.js, src/main/webapp/components/results/results.js
Changing column field names to make material-table happy.
If the table data doesn't contain a value for a column field, it checks to see if the field has a `.`. If it does, it tries to parse it as an object by looking for a field matching the string before the
`.`. 
Our fields do have a `.` in them but shouldn't be treated as objects. 
This is causing errors in material table.
We have `location.country-code` and `location` and material-table is trying to parse the location attribute for country-code and this is what's causing the error.
Fixes #362
=> Make material-data fields happy #362

src/main/webapp/components/results/results.js
Defaulting cells to be expandable so long texts values will be collapsed.
Image of collapsed metadata field:
=> Result table default to expandable cell
