src/main/webapp/basic-search.js
src/main/webapp/time-range.js

Material UI - error prop expects a boolean value

---

src/main/webapp/basic-search-helper.js
src/main/webapp/basic-search.js
src/main/webapp/line.js
src/main/webapp/location.js
src/main/webapp/location.stories.js
src/main/webapp/point-radius.js
src/main/webapp/polygon.js
src/main/webapp/time-range.js

Add Line to Location component

---

.gitignore
package.json
src/main/webapp/map-style.js
src/main/webapp/worldMap.js
src/main/webapp/worldMap.stories.js
yarn.lock

I added a World Map component with a storybook demonstrating drawing on the map in revelio. There are still styling issues (where do I get colors so the icons are readable?) and the map component is very incomplete. However, you can use the full functionality of GeospatialDraw to draw a search geo.
The branch of GeospatialDraw I'm using is:
https://github.com/connexta/geospatialdraw/tree/revelio

Added World Map component.

---

package.json
src/main/webapp/query-advanced/filter/filter-dropdowns.tsx
src/main/webapp/query-advanced/filter/filter-group.tsx
src/main/webapp/query-advanced/filter/filter-utils.tsx
src/main/webapp/query-advanced/filter/filter.tsx
src/main/webapp/query-advanced/filter/operator.tsx
src/main/webapp/query-advanced/query-advanced.stories.tsx
src/main/webapp/query-advanced/query-advanced.tsx
src/main/webapp/react-hooks/use-anchor-el.tsx
yarn.lock

I'm going to do inputs in a separate PR.
I need help with styling :smile: :

Add Query Advanced Base

---

src/main/webapp/basic-search-helper.js
src/main/webapp/query-advanced/filter-input/date-filter.tsx
src/main/webapp/query-advanced/filter-input/location-filter.tsx
src/main/webapp/query-advanced/filter-input/metacard-types.tsx
src/main/webapp/query-advanced/filter-input/text-filter.tsx
src/main/webapp/query-advanced/filter/filter-dropdowns.tsx
src/main/webapp/query-advanced/filter/filter-group.tsx
src/main/webapp/query-advanced/filter/filter-utils.tsx
src/main/webapp/query-advanced/filter/filter.tsx
src/main/webapp/query-advanced/query-advanced.stories.tsx

Changes output to be in valid filterTree structure:
converting {attribute, comparator value} => {property, type, value}
Adds Base Input Component
Notes:
Location Input - onChange should be called once location is valid
Date Input - will not trigger onChange. working on getting validation to work on that

INV-18 Produce FilterTree Data Structure

---

src/main/webapp/query-advanced/filter-input/date-filter.tsx
src/main/webapp/query-advanced/filter-input/location-filter.tsx
src/main/webapp/query-advanced/filter-input/text-filter.tsx
src/main/webapp/query-advanced/filter/dummyDefinitions.tsx
src/main/webapp/query-advanced/filter/filter-dropdowns.tsx
src/main/webapp/query-advanced/filter/filter-utils.tsx
src/main/webapp/query-advanced/filter/filter.tsx

Add some aliases to dropdowns too

Fix Typescript error

---

package.json
src/main/webapp/query-advanced/filter-input/location-filter.tsx
tsconfig.json
yarn.lock

Adds typescript compilation as part of build process

Add Typescript check to build

---

src/main/webapp/inspector/inspector.js
src/main/webapp/inspector/inspector.stories.js

Adding useApolloFallback to return the Container or the Component based on if Apollo Client is active
Updating story to reflect changes

INV-53 Apollo Fallback

---

.eslintrc.js
apollo.config.js
package.json
src/main/webapp/inspector/inspector.js
src/main/webapp/intrigue-api/gen-schema.js
src/main/webapp/intrigue-api/graphql.js
src/main/webapp/react-layout/react-layout.js
src/main/webapp/result-forms/route.js
src/main/webapp/simple-search.js
yarn.lock

Adds config for [Apollo GraphQL](https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo).

Adds eslint rules for GraphQL

---

src/main/webapp/query-advanced/filter-input/boolean-filter.tsx
src/main/webapp/query-advanced/filter-input/date-filter.tsx
src/main/webapp/query-advanced/filter-input/location-filter.tsx
src/main/webapp/query-advanced/filter-input/number-filter.tsx
src/main/webapp/query-advanced/filter-input/text-filter.tsx
src/main/webapp/query-advanced/filter/dummyDefinitions.tsx
src/main/webapp/query-advanced/filter/filter-dropdowns.tsx
src/main/webapp/query-advanced/filter/filter-utils.tsx
src/main/webapp/query-advanced/filter/filter.tsx

Adds Boolean and Number Inputs
Still need to:
Integrate better with date/location inputs
Add validation
Add the RANGE filter for numbers
Add the NEAR filter for strings

Add Boolean and Number Inputs

---

.eslintrc.js
package.json
src/main/webapp/query-advanced/filter-input/number-filter.tsx
src/main/webapp/query-advanced/filter-input/text-filter.tsx
src/main/webapp/query-advanced/filter/filter-dropdowns.tsx
src/main/webapp/query-advanced/filter/filter-group.tsx
src/main/webapp/query-advanced/filter/filter.tsx
src/main/webapp/query-advanced/filter/operator.tsx
src/main/webapp/query-advanced/filter/value-transformations.spec.js
src/main/webapp/query-advanced/filter/value-transformations.tsx
src/main/webapp/query-advanced/query-advanced-serialization.tsx
src/main/webapp/query-advanced/query-advanced.stories.tsx
src/main/webapp/query-advanced/query-advanced.tsx

Add NEAR and RANGE filters

---

src/main/webapp/basic-search.js
src/main/webapp/workspaces/workspaces.js

- Adds card around easy filter
- Adds ability to collapse filter card
- Moves remove to top right of card

Updates basic-search styles

---

src/main/webapp/basic-search-helper.js
src/main/webapp/query-advanced/filter-input/date-filter.tsx
src/main/webapp/query-advanced/filter-input/location-filter.tsx
src/main/webapp/query-advanced/filter/filter-utils.tsx
src/main/webapp/query-advanced/query-advanced-serialization.tsx
src/main/webapp/query-advanced/query-advanced.stories.tsx

Implement Date Filter in Query Advanced

---

src/main/webapp/basic-search.js
src/main/webapp/search-settings.js
src/main/webapp/search-settings.stories.js
src/main/webapp/sources.js
src/main/webapp/time-range.js

Changing `Add Filter` to `Add Option`
Adding `Result Forms` and `Sort Order` as options
Adding search settings for basic attribute and direction selectors
Removing extra comments from time-range
Adding a filtered Select for the the attribute selector
Updating basic-search to use sorts selected

INV-20 Search Settings

---

src/main/webapp/@storybook/react.js
src/main/webapp/about.stories.js
src/main/webapp/basic-search.stories.js
src/main/webapp/inspector/inspector.stories.js
src/main/webapp/location.stories.js
src/main/webapp/query-advanced/query-advanced.stories.tsx
src/main/webapp/query-status.stories.js
src/main/webapp/react-layout/react-layout.stories.js
src/main/webapp/result-forms/result-forms.js
src/main/webapp/result-forms/result-forms.stories.js
src/main/webapp/results/results.stories.js
src/main/webapp/routes.js
src/main/webapp/search-settings.stories.js
src/main/webapp/sources.stories.js
src/main/webapp/theme/index.js
src/main/webapp/theme/theme-dark.json
src/main/webapp/theme/theme-light.json
src/main/webapp/theme/theme-provider.js
src/main/webapp/theme/theme.js
src/main/webapp/theme/with-theme.js
src/main/webapp/thumbnail/thumbnail.stories.js
src/main/webapp/time-range.stories.js
src/main/webapp/user-settings/theme-settings.js
src/main/webapp/user-settings/user-settings.js
src/main/webapp/user-settings/user-settings.stories.js
src/main/webapp/workspaces/workspaces.stories.js
src/main/webapp/world-map-with-menu.stories.js
src/main/webapp/world-map.stories.js

- Adds user toggle for dark mode
- Adds product into in left nav menu

Starts theme work

---

src/main/webapp/basic-search.js
src/main/webapp/search-settings.js
src/main/webapp/search-settings.stories.js

Adding the ability for the user to select multiple sort orders

INV-20 Sort Order - Multiple Sorts

---

src/main/webapp/intrigue-api/graphql.js
src/main/webapp/routes.js
src/main/webapp/user.js
src/main/webapp/user.stories.js

Adds User Info

---

package.json
yarn.lock

Updating Material UI version to 4.6.1

Update Material UI version

---

package.json
src/main/webapp/query-advanced/filter/attribute-dropdown.tsx
src/main/webapp/search-settings.js
yarn.lock

Removing react-select in favor of Autocomplete

INV-20 Use Autocomplete in Sort Order

---

src/main/webapp/confirm-delete/confirm-delete.js
src/main/webapp/confirm-delete/confirm-delete.stories.js
src/main/webapp/confirm-delete/index.js
src/main/webapp/result-forms/result-forms.stories.js
src/main/webapp/result-forms/route.js

Pulls out confirm delete to be used by other components.

Extracts confirm delete from result forms

---

.dockerignore
Dockerfile
docker-compose.yml
package.json
src/main/graphql-server/helpers/renderer.js
src/main/graphql-server/middleware.js
src/main/graphql-server/server.js
src/main/webapp/app.js
src/main/webapp/intrigue-api/fetch.js
src/main/webapp/intrigue-api/gen-schema.js
src/main/webapp/intrigue-api/graphql.js
src/main/webapp/intrigue-api/schema-graphql.js
yarn.lock

- Adds docker file
- Adds docker compose
- Updates express server
- Removes Redux
- Adds more config to hit external DDF

Preparing Production Bundles With Docker

---

src/main/webapp/about.stories.js
src/main/webapp/confirm-delete/confirm-delete.stories.js
src/main/webapp/index-cards/index-cards.stories.js
src/main/webapp/maps/cluster-map.stories.js
src/main/webapp/maps/world-map-with-menu.stories.js
src/main/webapp/maps/world-map.stories.js
src/main/webapp/query-filters/query-filters.stories.tsx
src/main/webapp/query-status.stories.js
src/main/webapp/result-forms/result-forms.stories.js
src/main/webapp/sources.stories.js
src/main/webapp/spaced-linear-container.stories.js
src/main/webapp/thumbnail/thumbnail.stories.js

Fix Theming in Storybook

---

src/main/webapp/inspector/inspector.js

Updating Inspector to handle the different thumbnail value
Opening a new tab for actions selected
Minor reformatting

Inspector Fixes for thumbnails

---

.travis.yml
dockerDeploy.sh
package.json

- Adds automated & configurable logic for deploying our dockerized production bundles to the public registry
- Ensures deployment only upon successful merge into master
- Will be used to auto deploy and run into our AWS environment

Adding Automated Docker Deployments Into Travis Build

---

src/main/webapp/maps/world-map.js
src/main/webapp/workspaces/visualizations.js

The map will pan to selected results without zooming now.
Also updated coordinate display to use CoordinateValue component from location input.

Updated 2D Map visualization to pan instead of pan & and zoom on select.

---

package.json
schema.json
src/main/webapp/intrigue-api/attributes.json
src/main/webapp/intrigue-api/metacards/metacards.js
src/main/webapp/lists/index.js
src/main/webapp/lists/lists.js
src/main/webapp/lists/lists.stories.js
src/main/webapp/user-settings/hidden-results-settings.js
src/main/webapp/workspaces/workspaces.js
yarn.lock

Adds Lists

---

pom.xml
src/main/java/org/codice/ddf/attribute/enumerations/EnumerationExtractor.java
src/main/java/org/codice/ddf/attribute/enumerations/EnumerationMethods.java
src/main/resources/OSGI-INF/blueprint/blueprint.xml

Copied enumeration extractor from DDF so we can remove catalog ui dependency

Remove Catalog UI Dependency

---

src/main/java/org/codice/ddf/catalog/direct/CatalogMethods.java
src/main/webapp/intrigue-api/metacards/metacards.js

Front and backend aligned so should be non breaking

Name alignment

---

Dockerfile
docker-compose.yml
package.json
src/main/graphql-server/helpers/renderer.js
src/main/graphql-server/middleware.js
src/main/graphql-server/server.js
src/main/webapp/app.js
src/main/webapp/result-forms/route.js
src/main/webapp/routes.js
src/main/webapp/search-forms/editor.tsx
src/main/webapp/user.js
src/main/webapp/workspaces/workspaces.js
yarn.lock

Helps improve SSR to fix some of the loading issues and improper bundle injection we were seeing on the serverside.

Improving Serverside Rendering Functionality & Updating Docker 

---

src/main/webapp/histogram.js
src/main/webapp/histogram.stories.js
src/main/webapp/sample-multi-result.json
src/main/webapp/workspaces/visualizations.js

Adding Histogram that will display the number of hits for an
attribute's values
Adding a story for histogram
Adding Histogram to the visualizations menu
Updating sample-multi-result.json with more sample data

INV-35 Histogram

---

src/main/webapp/index-cards/index-cards.js
src/main/webapp/index-cards/index.js
src/main/webapp/lists/lists.js
src/main/webapp/lists/lists.stories.js

Use index cards for lists

---

src/main/webapp/histogram.js
src/main/webapp/workspaces/visualizations.js

Connecting the selection interface with histogram.
Now when clicking on a histogram bucket, the selection interface will be updated to those results

INV-35 Connecting Histogram and Selection Interface

---

package.json
yarn.lock

Fix windows compatibility issues

---

src/main/webapp/basic-search.js
src/main/webapp/index-cards/index-cards.js
src/main/webapp/workspaces/query-selector.js
src/main/webapp/workspaces/sample-queries.json
src/main/webapp/workspaces/workspaces.js
src/main/webapp/workspaces/workspaces.stories.js

Workspace query and result updates

---

src/main/webapp/gallery/gallery.js
src/main/webapp/gallery/gallery.stories.js
src/main/webapp/gallery/index.js
src/main/webapp/inspector/index.js
src/main/webapp/sample-multi-result.json
src/main/webapp/workspaces/visualizations.js

Initial gallery implementation

---

.travis.yml

This reverts commit 0fbbc2a8b139e6fbe03298885bc3d408cac497d8.

Turn on maven build

---

src/main/webapp/intrigue-api/context.js
src/main/webapp/intrigue-api/login/login.js
src/main/webapp/login/container.js

Fixes the issue where you can't have a tab of ddf and revelio open at the same time.

Fixing auth between revelio and ddf

---

src/main/webapp/login/container.js
src/main/webapp/login/login.js

Erroring with invalid credentials

---

src/main/webapp/index-cards/index-cards.js

Highlights whole index card on hover

Update index card styling

---

src/main/webapp/query-schedule.stories.tsx
src/main/webapp/query-schedule.tsx

Screenshots: 
Off:
Once, no deliveries:
Once, with delivery
Periodically with delivery time (and on dark mode)

Add Query Schedule Component

---

src/main/webapp/@storybook/use-state.js
src/main/webapp/query-builder/query-builder.tsx
src/main/webapp/search-forms/container.tsx
src/main/webapp/search-forms/editor.tsx
src/main/webapp/search-forms/route.tsx
src/main/webapp/search-forms/search-forms.stories.tsx

This will allow us to eventually use both basic and advanced search to edit queries in workspaces.

Make search form editor take in a query builder

---

src/main/webapp/query-builder/filter-inputs/number-filter.tsx
src/main/webapp/query-builder/filter-inputs/text-filter.tsx
src/main/webapp/query-builder/filter/attribute-dropdown.tsx
src/main/webapp/query-builder/filter/comparator-dropdown.tsx
src/main/webapp/query-builder/filter/filter-group.tsx
src/main/webapp/query-builder/filter/index.tsx
src/main/webapp/query-builder/filter/individual-filter.tsx
src/main/webapp/query-builder/query-builder.tsx
src/main/webapp/query-builder/types.tsx

Each component should have it's own reference to attribute definitions.
Also fixes issues with the number filter when entering negative numbers or floats.

Remove prop drilling for Attribute Definitions

---

package.json
src/main/webapp/error.stories.tsx
src/main/webapp/error.tsx
src/main/webapp/faceted-dropdown.tsx
src/main/webapp/query-builder/filter/attribute-dropdown.tsx
src/main/webapp/query-builder/filter/comparator-dropdown.tsx
src/main/webapp/query-builder/filter/individual-filter.tsx
src/main/webapp/result-forms/route.js
src/main/webapp/retry/retry.js
src/main/webapp/search-forms/container.tsx
src/main/webapp/search-forms/route.tsx
src/main/webapp/search/details.js
src/main/webapp/search/results.js
src/main/webapp/sort-order.js
src/main/webapp/sources.js
src/main/webapp/user-settings/hidden-results-settings.js
src/main/webapp/user-settings/result-form-select.js
src/main/webapp/user-settings/user-settings.js
src/main/webapp/user.js
src/main/webapp/workspaces/workspaces.js
yarn.lock

Add Centralized Error Component

---

src/main/webapp/index-cards/index-cards.js
src/main/webapp/result-forms/route.js
src/main/webapp/search-forms/route.tsx
src/main/webapp/workspaces/workspaces.js

Also Adds Delete Functionality to Workspaces
fixes: https://github.com/connexta/revelio/issues/220

Make Delete Modal Message Configurable

---

schema.json
src/main/webapp/basic-search.js
src/main/webapp/gallery/gallery.js
src/main/webapp/gallery/gallery.stories.js
src/main/webapp/gen-results.js
src/main/webapp/histogram.js
src/main/webapp/inspector/inspector.js
src/main/webapp/intrigue-api/metacards/metacards.js
src/main/webapp/intrigue-api/test.js
src/main/webapp/intrigue-api/user/user.js
src/main/webapp/query-builder/query-builder.tsx
src/main/webapp/query-builder/query-settings.tsx
src/main/webapp/query-builder/types.tsx
src/main/webapp/react-hooks/use-query-executor.js
src/main/webapp/results/results.js
src/main/webapp/sample-multi-result.json
src/main/webapp/sample-result.json
src/main/webapp/search-forms/editor.tsx
src/main/webapp/simple-search.js
src/main/webapp/sort-order.js
src/main/webapp/sort-order.stories.js
src/main/webapp/sources.js
src/main/webapp/sources.stories.js
src/main/webapp/user-settings/search-settings.js
src/main/webapp/user-settings/user-settings.js
src/main/webapp/workspaces/visualizations.js
src/main/webapp/workspaces/workspaces.js

Revelio counterpart to this rpc [pr](https://github.com/connexta/ddf-jsonrpc/pull/2)
until https://github.com/connexta/ddf-jsonrpc/pull/2 gets in

Rpc metacard attribute inconsistency 

---

package.json
yarn.lock

Removing dependency because it's already included in @material-ui/core
https://material-ui.com/styles/basics/#installation

Remove @material-ui/styles

---

src/main/webapp/components/query-editor/index.tsx
src/main/webapp/components/query-editor/query-editor.stories.js
src/main/webapp/components/query-editor/query-editor.tsx
src/main/webapp/components/query-selector/query-selector.js
src/main/webapp/components/query-selector/query-selector.stories.js
src/main/webapp/components/workspaces/workspaces.js
src/main/webapp/react-hooks/use-query-executor.js
src/main/webapp/sample-data/sample-queries.json

- Updates query selector to take in a query builder for queries (advanced, basic, etc.)
- Changes made to queries are saved locally between edits of different queries

Update query selector

---

src/main/webapp/components/user-settings/result-form-select.js
src/main/webapp/intrigue-api/metacards/metacards.js

Fixes https://github.com/connexta/revelio/issues/263

Add Result Forms Functionality to Queries

---

schema.json
src/main/webapp/components/notification/notification.js
src/main/webapp/components/result-forms/route.js
src/main/webapp/components/search-forms/route.tsx
src/main/webapp/components/workspaces/subscribe.js
src/main/webapp/components/workspaces/workspaces.js
src/main/webapp/intrigue-api/metacards/metacards.js

Add Workspace subscriptions

---

schema.json
src/main/webapp/components/index-cards/index-cards.js
src/main/webapp/components/index-cards/index-cards.stories.js
src/main/webapp/components/search-forms/container.tsx
src/main/webapp/components/search-forms/route.tsx
src/main/webapp/components/workspaces/workspaces.js
src/main/webapp/intrigue-api/metacards/metacards.js

Starts: https://github.com/connexta/revelio/issues/269
Also fixes a bug where workspaces aren't showing the owner
Screenshot:

Display the Default Search Form

---

src/main/webapp/components/query-builder/query-builder.tsx
src/main/webapp/components/query-editor/query-editor.tsx
src/main/webapp/components/search-forms/editor.tsx

Fixes regressions introduced by https://github.com/connexta/revelio/pull/270.
- Add header section back into search forms editor
- fix console errors

Fix search forms

---

src/main/webapp/components/workspaces/workspaces.js

Wrapping the React Router Link component around index cards results in a click area that extends past the border of the index card. This pr removes the link wrapper and redirects using the useHistory hook instead.

Fix workspace index cards click area

---

src/main/webapp/components/basic-search/basic-search.js
src/main/webapp/components/query-editor/query-editor.tsx
src/main/webapp/components/query-selector/query-selector.js
src/main/webapp/components/workspaces/workspaces.js

Adds switching between basic and advanced search in query editor

---

src/main/webapp/components/confirm-delete/confirm-delete.js
src/main/webapp/components/confirm-delete/confirm-delete.stories.js
src/main/webapp/components/confirm-delete/index.js
src/main/webapp/components/index-cards/index-cards.js
src/main/webapp/components/index-cards/metacard-interactions/edit-metacard-interaction.tsx
src/main/webapp/components/index-cards/metacard-interactions/index.tsx
src/main/webapp/components/metacard-interaction/index.tsx
src/main/webapp/components/metacard-interaction/metacard-interaction.tsx
src/main/webapp/components/metacard-interaction/metacard-interactions-dropdown.tsx
src/main/webapp/components/result-forms/route.js
src/main/webapp/components/search-forms/route.tsx
src/main/webapp/components/sharing/sharing-modal.js

Allow for Metacard Actions in a Dropdown

---

package.json
src/main/webapp/components/results/results.js
src/main/webapp/components/results/results.stories.js
yarn.lock

This PR is for using material-table for our results table.
This would replace the custom built results table
Material-table provides built-in functionality such as column reordering, sorting, search bar for filtering.

Results table -> Material Table

---

src/main/webapp/components/index-cards/metacard-interactions/duplicate-metacard-interaction.js
src/main/webapp/components/index-cards/metacard-interactions/index.tsx
src/main/webapp/components/workspaces/subscribe.js
src/main/webapp/components/workspaces/workspaces.js

Added interactions to the workspaces route

---

src/main/webapp/components/sources-info-local/index.js
src/main/webapp/components/sources-info-local/sources-info-local.js
src/main/webapp/components/sources-info/poll-interval.js
src/main/webapp/components/sources-info/sources-info.js

Add results from faceted query to local sources in the search/catalog/sources page

#215 Update the sources view to issue faceted queries and display them as sources 

---

src/main/webapp/components/query-manager/query-manager.stories.tsx
src/main/webapp/components/query-manager/query-manager.tsx
src/main/webapp/components/query-manager/types.tsx
src/main/webapp/components/workspace/hooks/index.tsx
src/main/webapp/components/workspace/hooks/use-save-query.tsx
src/main/webapp/components/workspace/workspace.js

#303
edit: oops, ^ that's a duplicate issue #271

Save edited queries on search

---

src/main/webapp/components/workspaces/filter-workspaces.js
src/main/webapp/components/workspaces/workspaces.js

Added workspace filtering

---

package.json
src/main/webapp/components/metacard-interaction/metacard-interactions-dropdown.tsx
src/main/webapp/components/results/results.js
src/main/webapp/components/search-forms/container.tsx
src/main/webapp/intrigue-api/base-typedefs.js
src/main/webapp/intrigue-api/merge-modules.js
src/main/webapp/intrigue-api/schema.js
src/main/webapp/react-hooks/use-user-prefs.tsx

Fixes: #305 
Fixes: #309
Also fixes this error in the vscode console:

Minor Restructure and Version Bump

---

src/main/webapp/components/query-builder/query-builder.tsx
src/main/webapp/components/query-manager/query-editor-popover.tsx
src/main/webapp/components/text-search/index.tsx
src/main/webapp/components/text-search/text-search.stories.tsx
src/main/webapp/components/text-search/text-search.tsx

Adds Text Search

---

src/main/webapp/components/basic-search/basic-search.js

Populate sources and sorts for basic search queries on refresh

---

src/main/webapp/components/faceted-dropdown/index.tsx

Adding Match Types to basic search freezes the page #312

---

src/main/webapp/components/search-form-select/search-form-select.stories.tsx
src/main/webapp/components/search-form-select/search-form-select.tsx
src/main/webapp/utils/matches-filter.tsx

PR was getting big so breaking it up into two chunks in an effort to be more readable. Network Logic and moving this into the query interactions will be in a future PR.
Screenshot:

Base Search Form Select

---

src/main/webapp/components/query-manager/query-editor-popover.tsx
src/main/webapp/components/search-form-select/search-form-select.stories.tsx
src/main/webapp/components/search-form-select/search-form-select.tsx

Fixes: https://github.com/connexta/revelio/issues/327

Add Search Form Select to Query Interactions

---

schema.json
src/main/webapp/components/result-export/result-export-action.js
src/main/webapp/components/result-export/result-export.js
src/main/webapp/components/result-export/result-export.stories.js
src/main/webapp/components/results/result-index-cards.js
src/main/webapp/intrigue-api/metacards/metacards.js

Export result

---

src/main/webapp/components/workspace/hooks/use-save-workspace.tsx
src/main/webapp/components/workspace/workspace-title.js
src/main/webapp/components/workspace/workspace.js

Editable workspace title

---

src/main/webapp/components/nav-bar/index.js
src/main/webapp/components/nav-bar/nav-bar-context.js
src/main/webapp/components/nav-bar/nav-bar.js
src/main/webapp/components/nav-menu/index.js
src/main/webapp/components/nav-menu/nav-menu.js
src/main/webapp/components/query-manager/add-query.tsx
src/main/webapp/components/query-manager/query-manager.stories.tsx
src/main/webapp/nav-bar-context.js
src/main/webapp/routes.js

Each component broken into it's own commit

Break out Nav Bar and Nav Menu

---

src/main/webapp/components/query-editor/query-editor.tsx
src/main/webapp/components/query-manager/query-editor-popover.tsx
src/main/webapp/components/query-manager/query-manager.stories.tsx
src/main/webapp/components/query-manager/query-manager.tsx
src/main/webapp/components/query-manager/types.tsx
src/main/webapp/components/result-export/result-export.js

Duplicate query

---

src/main/webapp/components/workspace/hooks/use-save-workspace.tsx
src/main/webapp/components/workspace/workspace-title.js
src/main/webapp/components/workspace/workspace.js

Partial updating can now be done due to: https://github.com/connexta/revelio/pull/341

Updates save workspace hook

---

src/main/webapp/components/result-export/result-export-action.js
src/main/webapp/components/results/result-checkbox.js
src/main/webapp/components/results/result-index-cards.js

Typo and styling changes

---

src/main/webapp/components/metacard-interaction/metacard-interactions-dropdown.tsx
src/main/webapp/components/query-manager/query-manager.tsx
src/main/webapp/components/result-export/result-export-action.js
src/main/webapp/components/results/result-index-cards.js

Adding result interaction dropdown

---

src/main/webapp/components/index-cards/index-cards.js
src/main/webapp/components/react-golden-layout/react-golden-layout.js
src/main/webapp/components/results/result-index-cards.js

Result title wrap, selected tab clearer

---

src/main/webapp/components/query-builder/filter/filter-utils.tsx
src/main/webapp/components/workspace/filters.js
src/main/webapp/components/workspace/section.js
src/main/webapp/components/workspace/workspace.js

Added the ability to filter results in a workspace.

Added filters to workspace results

---

src/main/webapp/components/results/results.js
src/main/webapp/components/search-forms/editor.tsx
src/main/webapp/components/workspace/workspace.js
src/main/webapp/components/workspaces/filter-workspaces.js

Fixes: #357 
Fixes: #358 
Fixes #354

Addressing some ux feedback

---

src/main/webapp/components/query-manager/add-query.tsx
src/main/webapp/components/query-manager/index.js
src/main/webapp/components/query-manager/query-manager.tsx
src/main/webapp/components/query-manager/types.tsx
src/main/webapp/components/workspace/workspace.js

The create search button was not showing when the 'Lists' tab was active

Create search button should always be visible in a workspace

---

src/main/webapp/components/index-cards/metacard-interactions/index.tsx
src/main/webapp/components/index-cards/metacard-interactions/refresh-metacard-interaction.js
src/main/webapp/components/query-manager/query-manager.tsx
src/main/webapp/components/query-manager/types.tsx
src/main/webapp/components/workspace/workspace.js
src/main/webapp/react-hooks/use-query-executor.js

Adds refresh result count interaction

---

src/main/webapp/components/results/results.js
src/main/webapp/components/results/results.stories.js

Adding attribute aliases to the results table.
Using the attributeAliases map from systemProperties.
Updating the results table story with attribute aliases

Attribute Aliases

---

.travis.yml

build is passing but not deploying to http://connexta.com/revelio/ properly

Update Deploy Dir
